Update build extension action

diff --git a/build-extension/action.yml b/build-extension/action.yml
--- a/build-extension/action.yml
+++ b/build-extension/action.yml
@@ -35,6 +35,18 @@ runs:
       cat "./${{ inputs.extension-path }}/ExtensionManifest.json" | dos2unix | perl -pe 'chomp if eof' >> $GITHUB_ENV
       echo -e "\n${delim}" >> $GITHUB_ENV
 
+  - name: Print Extension Info
+    shell: bash
+    run: |
+    echo "[Extension Info Values]"
+    echo "Version                  : ${{ fromJSON(env.manifest).version }}"
+    echo "Type                     : ${{ fromJSON(env.manifest).type }}"
+    echo "Package ID               : ${{ fromJSON(env.manifest).packageId }}"
+    echo "GitHub Repository        : ${{ fromJSON(env.manifest).repository }}"
+    echo "Name                     : ${{ fromJSON(env.manifest).name }}"
+    echo "Author                   : ${{ fromJSON(env.manifest).author }}"
+    echo "Target Plugin API Version: ${{ fromJSON(env.manifest).target-plugin-api-version }}"
+
   - name: Validate Extension Info
     if: |
       fromJSON(env.manifest).type == '' || 
@@ -45,14 +57,7 @@ runs:
       fromJSON(env.manifest).version == '' ||
       fromJSON(env.manifest).target-plugin-api-version == ''
     shell: bash
-    run: |
-      echo "[Extension Info Values]"
-      echo "Version                  : ${{ fromJSON(env.manifest).version }}"
-      echo "Type                     : ${{ fromJSON(env.manifest).type }}"
-      echo "Package ID               : ${{ fromJSON(env.manifest).packageId }}"
-      echo "GitHub Repository        : ${{ fromJSON(env.manifest).repository }}"
-      echo "Target Plugin API Version: ${{ fromJSON(env.manifest).target-plugin-api-version }}"
-      echo "::error file=ExtensionManifest.json::Invalid manifest! Required attributes [version, type, packageId, target-plugin-api-version]" && exit 1
+    run: echo "::error file=ExtensionManifest.json::Invalid manifest! Required attributes [version, type, packageId, target-plugin-api-version]" && exit 1
 
   - name: Checkout Macro Deck Repository
     uses: actions/checkout@v3
@@ -89,8 +94,8 @@ runs:
     working-directory: ./macro-deck
     shell: bash
     run : |
-      xmlstarlet ed -P -L --delete '//Target[@Name="PreBuild"]' *.csproj
-      xmlstarlet ed -P -L --delete '//Target[@Name="PostBuild"]' *.csproj
+      xmlstarlet ed -P -L --delete '//Target[@Name="PreBuild"]' *.csproj 2>/dev/null || true
+      xmlstarlet ed -P -L --delete '//Target[@Name="PostBuild"]' *.csproj 2>/dev/null || true
 
   - name: "[Plugin] Remove COM Reference"
     if: fromJSON(env.manifest).type == 'Plugin' || fromJSON(env.manifest).type == 0
